### ISSUE TITLE
images

### ISSUE THREAD

**Issue by melund** [AnyBody/GRF-prediction#1]
![image](https://cloud.githubusercontent.com/assets/1038978/19969105/9a7834b6-a1d7-11e6-8880-26bb8fbc489e.png)

![image](https://cloud.githubusercontent.com/assets/1038978/19969138/ba3a37f4-a1d7-11e6-9998-5b76ecaf4de2.png)

![image](https://cloud.githubusercontent.com/assets/1038978/19969209/082f83a6-a1d8-11e6-8ea7-7915bb817025.png)

**Comment by jiangzong** [comment]
Excuse me. I'm wondering why  there comes the following error when I load the main file. 
```
Loading  Main  :  "D:\ForQiao\Reduced-G\anybody_tutorials\AMMRV1.0\Application\Examples\GRF-prediction-master\MoCap_FullBody.main.any"
Scanning...
Parsing...
ERROR(SCR.PRS11) :   D:/F..o/R..G/a..s/A..0/A..n/E..s/G..r/I..t/Markers.any  :   '(' unexpected
Model loading skipped
```

**Comment by jiangzong** [comment]
Excuse me.  "libdef.any" says the following:
```
// Please change this to emsure it points to the body model 
// repository you want to use. 
#include "<ANYBODY_PATH_INSTALLDIR>/AMMR/Application/libdef.any"
```
However, I fail to found any file named "libdef.any"in my " install path /AMMR/Application".
So, what's the function of  "libdef.any" ?

**Comment by melund** [comment]
Thanks for reporting this @jiangzong.  I think I know what the problem is. You are most likely using an old version of the AnyBody Modeling System.  

It looks like you are using AMMR version 1.0, which came with AnyBody Modeling System version 3 or 4. 

I am sorry. But you can't use the GRF prediction models with such old versions of AnyBody. You need at least version 6 or 7. 
 
Hope it helps.

**Comment by jiangzong** [comment]
Thanks a lot. We have nothing else but AMMR Version1.0 currently. I'll seek for my tutor's support for a  higher version. 
Thanks for your reply.

**Comment by jiangzong** [comment]
@melund Excuse me.
I'm writing for consulting the difference between  the **JointReactionMoment** and the **NetMoment** of a same joint in the Output of the GRF-Prediction demo. 
For instance, 
                 Output.BodyModel.Left.Leg.MomentMeasure.AnkleJointReactionMoments ​
                  and
                Output.BodyModel.Left.Leg.MomentMeasure.AnklePlantarFlexionNetMoment

What's more, there are JointReactionMoment and the NetMoment for  the Ankle joints and Knee Joints in the output. However, why only the NetMoment for the Hip joint can be found ? Is there anything different for the Hip joint?

**Comment by melund** [comment]
@jiangzong I think you should ask this kind of questions over on the [AnyScript.org forums](http://forum.anyscript.org/). It not related to this GRF model, and people on the forum  can answer much better than I. 

I am just guessing based on the names, but I think the JointReactionMoments are the moments provided by the joint constraints. A revolute joint would have 2 reaction moments, and 3 reaction forces. The last degree of freedom is free. 

This would also explain why the hip joint has no reaction moments. Because it is spherical joint, it only has three reaction forces, and all the rotational degrees of freedom are free.

**Comment by jiangzong** [comment]
@melund Thank you very much.
