### ISSUE TITLE
Error loading model in AnyBody version : 4. 0. 2. 697 

### ISSUE THREAD

**Issue by totofaz** [AnyBody/GRF-prediction#2]
Hello, I tried to do as in the end of youtube webcast video "Ground Reaction Force Prediction With The AnyBody Modeling System", the problem is that I could not load the model, when I got it right i got "##IDX : Unexpected." which lead to the thread   "#define __CREATE_CC_NODE__(IDX) NodesBaseFrame = { AnyRefNode Node##IDX = {sRel = ..Targets[IDX]; AnyDrawNode Drw = { RGB = {1, 0, 1}; ScaleXYZ= 0.005*{1, 1, 1}; Opacity = 0.5; }; };}; AnyRefNode &Node##IDX = NodesBaseFrame.Node##IDX"

Any idea what should I do to make it load the MoCap model?
Thank you.

**Comment by melund** [comment]
Hi @totofaz. Thanks for reporting. 

I am afraid you are out of luck. The model uses a number of features which was introduced in version 6 of the AnyBody Modeling System. 

Version 4.0.2 that you are using is roughly 8 years old.

**Comment by totofaz** [comment]
Thank you for your feedback, I will try to acquire a newer version of
anybody.
Have a nice day.
