### ISSUE TITLE
Sports related activity

### ISSUE THREAD

**Issue by totofaz** [AnyBody/GRF-prediction#3]
Hello, it's me again. I managed to get a trial version of Anybody 6.1.
I wanted to ask how could I get the model that you obtained by motion capture?
I am required to do a project for school and that model would help me allot.
Thank you.

**Comment by melund** [comment]
@totofaz. The example model here only contains gait. 

I expect you are referring to the sports related movements from the webcast. They were recorded as part of a research project by [Prof. Michael Skipper Andersen](http://personprofil.aau.dk/103093) and Sebastian Skals from Aalborg University. 

I don't have their data and I probably wouldn't be allowed to share it publicly on Github anyway.  You could try to contact the author directly:  https://link.springer.com/article/10.1007%2Fs11044-016-9537-4

**Comment by totofaz** [comment]
Thank you again.
